# Generated by Django 5.2.7 on 2025-10-21 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_text", models.TextField(help_text="Original wall config input")),
                ("num_teams", models.IntegerField(help_text="Number of construction teams")),
                ("start_date", models.DateField(help_text="Simulation start date")),
                ("total_days", models.IntegerField(help_text="Total construction days")),
                ("total_cost", models.DecimalField(decimal_places=2, help_text="Total cost in Gold Dragons", max_digits=15)),
                ("total_sections", models.IntegerField(help_text="Total number of wall sections")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "simulations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("team_lead", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        help_text="Simulation this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="profiles.simulation",
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "ordering": ["-created_at"],
                "unique_together": {("simulation", "name")},
            },
        ),
        migrations.CreateModel(
            name="WallSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section_name", models.CharField(max_length=255)),
                ("initial_height", models.IntegerField(blank=True, help_text="Initial height in feet (0-30) for simulation", null=True)),
                ("current_height", models.IntegerField(blank=True, help_text="Current height in feet during simulation", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wall_sections", to="profiles.profile")),
            ],
            options={
                "db_table": "wall_sections",
                "ordering": ["-created_at"],
                "unique_together": {("profile", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("feet_built", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ice_cubic_yards", models.DecimalField(decimal_places=2, help_text="195 cubic yards per foot", max_digits=10)),
                ("cost_gold_dragons", models.DecimalField(decimal_places=2, help_text="1900 Gold Dragons per cubic yard", max_digits=15)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("wall_section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_progress", to="profiles.wallsection")),
            ],
            options={
                "db_table": "daily_progress",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="daily_progr_date_0991b4_idx"),
                    models.Index(fields=["wall_section", "date"], name="daily_progr_wall_se_96bc87_idx"),
                ],
                "unique_together": {("wall_section", "date")},
            },
        ),
    ]
