# Generated by Django 5.2.7 on 2025-10-20 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_add_simulation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallsection",
            name="start_position",
        ),
        migrations.RemoveField(
            model_name="wallsection",
            name="target_length_feet",
        ),
    ]
